### ISSUE TITLE
About the pretrained files

### ISSUE THREAD

**Issue by tangkail** [lxn96/ICPE#3]
I cannot find how to download the pre-trained file:resnet101_msra-6cc46731.pth, can you help me?

**Comment by lxn96** [comment]
You can use 'open-mmlab://detectron2/resnet101_caffe' in config, or download from the link:
https://download.openmmlab.com/pretrain/third_party/resnet101_msra-6cc46731.pth

**Comment by tangkail** [comment]
Thank you very much!



---Original---
From: "Xiaonan ***@***.***&gt;
Date: Mon, Apr 24, 2023 09:55 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [lxn96/ICPE] About the pretrained files (Issue #3)




 
You can use 'open-mmlab://detectron2/resnet50_caffe' in config, or download from the link:
 https://download.openmmlab.com/pretrain/third_party/resnet101_msra-6cc46731.pth
